server {
    listen       80;
    server_name  _;
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # Gzip settings
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript image/svg+xml;
    gzip_min_length 1000;

    # Static assets with caching
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # SPA fallback — semua route selain file fisik diarahkan ke index.html
    location / {
        try_files $uri /index.html;
    }
}