/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingDisplayRouteImport } from './routes/setting-display'
import { Route as PenggunaRouteImport } from './routes/pengguna'
import { Route as PanggilanRouteImport } from './routes/panggilan'
import { Route as LoketRouteImport } from './routes/loket'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as GrupKeamananRouteImport } from './routes/grup-keamanan'
import { Route as DisplayClientRouteImport } from './routes/display-client'
import { Route as AntrianRouteImport } from './routes/antrian'
import { Route as IndexRouteImport } from './routes/index'

const SettingDisplayRoute = SettingDisplayRouteImport.update({
  id: '/setting-display',
  path: '/setting-display',
  getParentRoute: () => rootRouteImport,
} as any)
const PenggunaRoute = PenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => rootRouteImport,
} as any)
const PanggilanRoute = PanggilanRouteImport.update({
  id: '/panggilan',
  path: '/panggilan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoketRoute = LoketRouteImport.update({
  id: '/loket',
  path: '/loket',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const GrupKeamananRoute = GrupKeamananRouteImport.update({
  id: '/grup-keamanan',
  path: '/grup-keamanan',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayClientRoute = DisplayClientRouteImport.update({
  id: '/display-client',
  path: '/display-client',
  getParentRoute: () => rootRouteImport,
} as any)
const AntrianRoute = AntrianRouteImport.update({
  id: '/antrian',
  path: '/antrian',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/antrian': typeof AntrianRoute
  '/display-client': typeof DisplayClientRoute
  '/grup-keamanan': typeof GrupKeamananRoute
  '/layanan': typeof LayananRoute
  '/login': typeof LoginRoute
  '/loket': typeof LoketRoute
  '/panggilan': typeof PanggilanRoute
  '/pengguna': typeof PenggunaRoute
  '/setting-display': typeof SettingDisplayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antrian': typeof AntrianRoute
  '/display-client': typeof DisplayClientRoute
  '/grup-keamanan': typeof GrupKeamananRoute
  '/layanan': typeof LayananRoute
  '/login': typeof LoginRoute
  '/loket': typeof LoketRoute
  '/panggilan': typeof PanggilanRoute
  '/pengguna': typeof PenggunaRoute
  '/setting-display': typeof SettingDisplayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/antrian': typeof AntrianRoute
  '/display-client': typeof DisplayClientRoute
  '/grup-keamanan': typeof GrupKeamananRoute
  '/layanan': typeof LayananRoute
  '/login': typeof LoginRoute
  '/loket': typeof LoketRoute
  '/panggilan': typeof PanggilanRoute
  '/pengguna': typeof PenggunaRoute
  '/setting-display': typeof SettingDisplayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/antrian'
    | '/display-client'
    | '/grup-keamanan'
    | '/layanan'
    | '/login'
    | '/loket'
    | '/panggilan'
    | '/pengguna'
    | '/setting-display'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/antrian'
    | '/display-client'
    | '/grup-keamanan'
    | '/layanan'
    | '/login'
    | '/loket'
    | '/panggilan'
    | '/pengguna'
    | '/setting-display'
  id:
    | '__root__'
    | '/'
    | '/antrian'
    | '/display-client'
    | '/grup-keamanan'
    | '/layanan'
    | '/login'
    | '/loket'
    | '/panggilan'
    | '/pengguna'
    | '/setting-display'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntrianRoute: typeof AntrianRoute
  DisplayClientRoute: typeof DisplayClientRoute
  GrupKeamananRoute: typeof GrupKeamananRoute
  LayananRoute: typeof LayananRoute
  LoginRoute: typeof LoginRoute
  LoketRoute: typeof LoketRoute
  PanggilanRoute: typeof PanggilanRoute
  PenggunaRoute: typeof PenggunaRoute
  SettingDisplayRoute: typeof SettingDisplayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setting-display': {
      id: '/setting-display'
      path: '/setting-display'
      fullPath: '/setting-display'
      preLoaderRoute: typeof SettingDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengguna': {
      id: '/pengguna'
      path: '/pengguna'
      fullPath: '/pengguna'
      preLoaderRoute: typeof PenggunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panggilan': {
      id: '/panggilan'
      path: '/panggilan'
      fullPath: '/panggilan'
      preLoaderRoute: typeof PanggilanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loket': {
      id: '/loket'
      path: '/loket'
      fullPath: '/loket'
      preLoaderRoute: typeof LoketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grup-keamanan': {
      id: '/grup-keamanan'
      path: '/grup-keamanan'
      fullPath: '/grup-keamanan'
      preLoaderRoute: typeof GrupKeamananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display-client': {
      id: '/display-client'
      path: '/display-client'
      fullPath: '/display-client'
      preLoaderRoute: typeof DisplayClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antrian': {
      id: '/antrian'
      path: '/antrian'
      fullPath: '/antrian'
      preLoaderRoute: typeof AntrianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntrianRoute: AntrianRoute,
  DisplayClientRoute: DisplayClientRoute,
  GrupKeamananRoute: GrupKeamananRoute,
  LayananRoute: LayananRoute,
  LoginRoute: LoginRoute,
  LoketRoute: LoketRoute,
  PanggilanRoute: PanggilanRoute,
  PenggunaRoute: PenggunaRoute,
  SettingDisplayRoute: SettingDisplayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
